### ISSUE TITLE
FM only tracks filament use on Spool 0

### ISSUE THREAD

**Issue by mpd352** [OllisGit/OctoPrint-FilamentManager#24] opened 2020-12-03 19:11 UTC
**Describe the bug**
I have a GeeeTech A10T, which is a three spool printer. Filament Manager is configured to allow me to select a specific spool from the spool database for each extruder. The correct number of extruders is set in Octoprint Setup, and the shared hotend flag is set.

**Expected behavior**
Filament usage should be tracked on Spool 1 and 2 as well

**Log file**
Drag and drop the octoprint.log here.
[octoprint Part 01.log](https://github.com/OllisGit/OctoPrint-FilamentManager/files/5638410/octoprint.Part.01.log)
[octoprint Part 02.log](https://github.com/OllisGit/OctoPrint-FilamentManager/files/5638411/octoprint.Part.02.log)

**Screenshots**
![Capture01](https://user-images.githubusercontent.com/41216685/101076498-b2554f80-3560-11eb-88b0-434d6497d234.JPG)
![Capture02](https://user-images.githubusercontent.com/41216685/101076501-b2ede600-3560-11eb-9a9a-aebc075ccc3b.JPG)
![Capture03](https://user-images.githubusercontent.com/41216685/101076503-b3867c80-3560-11eb-8f40-1df8b98bcd9a.JPG)

**Additional context**

**Comment by WarrenSchultz** [comment] 2021-01-14 18:30
Confirmed, seeing this issue as well, came here to file a bug. :)

**Comment by OllisGit** [comment] 2021-01-28 21:03
As mentioned in the other ticket please provide the corresponding gcode file, so that I am able to reproduce the issue in my environment.
@WarrenSchultz same question to you:
- screenshot of what you expect and the gcode file.

**Comment by mpd352** [comment] 2021-01-28 21:13
Sorry, thought I had uploaded these. 


[Ornaments 01_colored.txt](https://github.com/OllisGit/OctoPrint-FilamentManager/files/5890007/Ornaments.01_colored.txt)
![Oraments 01 colored](https://user-images.githubusercontent.com/41216685/106199522-cf7a5900-6172-11eb-8504-d771e519e9eb.JPG)

The forum won't let me upload a gcode file so I renamed Ornaments.01_colored.gcode to Ornaments.01_colored.txt

**Comment by OllisGit** [comment] 2021-01-28 23:10
Hi @mpd352 ,
I looked into the gcode and there is only T2 used and not T1.
![image](https://user-images.githubusercontent.com/24205767/106210000-4ee54800-61c6-11eb-9a95-2f6f95bea841.png)

This is also detected by OctoPrint itself, only Tool 2 is shown:
![image](https://user-images.githubusercontent.com/24205767/106209834-088fe900-61c6-11eb-9e21-64e583113102.png)

**Comment by WarrenSchultz** [comment] 2021-01-28 23:35
@OllisGit 
![image](https://user-images.githubusercontent.com/8450968/106211737-3578d780-6197-11eb-8f8a-2d1f15d1def6.png)
[LeftAnchorBlock_0.2mm_ABS_MK3SMMU2S_12h19m.gcode.zip](https://github.com/OllisGit/OctoPrint-FilamentManager/files/5890605/LeftAnchorBlock_0.2mm_ABS_MK3SMMU2S_12h19m.gcode.zip)

![image](https://user-images.githubusercontent.com/8450968/106211850-63f6b280-6197-11eb-966b-0277347a0c80.png)

The print is set to use Tool 4, the Filament Manager has Tool 4 showing the correct filament. Printing, everything works well, but the remaining filament counter for tool 4 (in this case, ABS) is not decremented with use. On a print using T0 (PLA in this case), it would work fine.

**Comment by OllisGit** [comment] 2021-01-29 16:06
Hi @WarrenSchultz,

I did some test and for your provided gcode the FilamentManager only detect ~55mm for Tool4, but it should 76997.75167999369.

Currently I am rewriting the whole filamenttracker-logic, because it didn't work in some cases, "obviously" ;-)
Will be finished this weekend...hopefully

**Comment by mpd352** [comment] 2021-01-29 19:01
> Hi @WarrenSchultz,
> 
> I did some test and for your provided gcode the FilamentManager only detect ~55mm for Tool4, but it should 76997.75167999369.
> 
> Currently I am rewriting the whole filamenttracker-logic, because it didn't work in some cases, "obviously" ;-)
> Will be finished this weekend...hopefully

Thank you!  We appreciate the time and effort.

**Comment by OllisGit** [comment] 2021-01-29 21:02
Hi,

new release 1.7.1 is out and should fix some material tracking issue.
After resuming a multi extruder print, the following tracked filament is assigned to tool0. To fix that issue I reimplemented the whole material tracking (maybe it solves other issues as well ;-). 

Please retest with the new version and give me a  feedback!

**Closed** 2021-04-19 19:04 UTC
Labels: BUG:FILAMENT TRACKING, status: waitingForTestFeedback
